{% set version = "0" %}

package:
  name: r-cdseq
  version: {{ version }}

source:
#   url:
#     - https://github.com/kkang7/CDSeq_R_Package/archive/refs/heads/master.zip
#   sha256: 78bbd78141cde66989493cd4bfc16d904877ff1e389dec55fc8666644b1308ba
  url:
    - https://github.com/grst/CDSeq_R_Package/archive/refs/heads/master.zip
  sha256: 3c9709e658ee4b46d2f7305feeb0581a9f6efc95488bf95ec32e57366d2c3dcb

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - r-base
    - r-roxygen2 >=6.0.1
    - r-rcpp >=1.0.3
    - r-mass
    - r-foreach
    - r-doparallel
    - r-dirmult
    - r-rcppthread
    - r-iterators
    - r-seurat
    - r-ggplot2
    - r-magrittr
    - r-dplyr
    - r-rlang
    - r-matrix
    - r-matrixstats
    - r-ggpubr
    - r-pheatmap
    - r-harmony
    - r-gplots
    - r-clue
    - bioconductor-biobase
    - r-qlcmatrix
  run:
    - r-base
    - r-rcpp >=1.0.3
    - r-mass
    - r-foreach
    - r-doparallel
    - r-dirmult
    - r-rcppthread
    - r-iterators
    - r-seurat
    - r-ggplot2
    - r-magrittr
    - r-dplyr
    - r-rlang
    - r-matrix
    - r-matrixstats
    - r-ggpubr
    - r-pheatmap
    - r-harmony
    - r-gplots
    - r-clue
    - bioconductor-biobase
    - r-qlcmatrix

test:
  commands:
    - $R -e "library('CDSeq')"

about:
  home: https://github.com/kkang7/CDSeq_R_Package
  license: GPL-3
  summary: "Estimate cell-type-specific gene expression profiles and sample-specific cell-type proportions simultaneously using bulk sequencing data. Kang et al. (2019) <doi:10.1371/journal.pcbi.1007510>."
  license_family: GPL
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - PelzKo
  identifiers:
    - doi:10.1371/journal.pcbi.1007510
